services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=vibe_chat
    ports:
      - '5432:5432'
    volumes:
      - monday-chat-db:/var/lib/mysql

  dbgate:
    build: docker
    image: dbgate/dbgate:alpine
    ports:
      - 3100:3000

    volumes:
      - monday-chat-dbgate-data:/root/.dbgate

  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  monday-chat-dbgate-data:
  monday-chat-db:
  minio_data:
