services:

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=monday_chat
    ports:
      - '5432:5432'
    volumes:
      - monday-chat-db:/var/lib/mysql

  dbgate:
    build: docker
    image: dbgate/dbgate:alpine
    ports:
      - 3100:3000

    volumes:
      - monday-chat-dbgate-data:/root/.dbgate
volumes:
  monday-chat-dbgate-data:
  monday-chat-db:
