services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=vibe_chat
    ports:
      - '5432:5432'
    volumes:
      - vibe_chat_db:/var/lib/postgresql/data

  dbgate:
    build: docker
    image: dbgate/dbgate:alpine
    ports:
      - 3100:3000

  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  vibe_chat_db:
  minio_data:
