import { Meta, StoryObj } from '@storybook/react';
import { ConnectedGreenApiInstance } from '.';
import { GreenApiInstanceStatus } from '@monday-whatsapp/shared-types';
import { useState } from 'react';

const meta: Meta<typeof ConnectedGreenApiInstance> = {
  component: ConnectedGreenApiInstance,
  argTypes: {},
  args: {},
};

export default meta;
type Story = StoryObj<typeof ConnectedGreenApiInstance>;

export const Connected: Story = {
  render(args) {
    const [pendingDisconnect, setPendingDisconnect] = useState<boolean>();
    return (
      <ConnectedGreenApiInstance
        {...args}
        pendingDisconnect={pendingDisconnect}
        onDisconnectWhatsapp={() => {
          setPendingDisconnect(true);
        }}
        phoneNumber={'0542090500'}
      />
    );
  },
  args: {
    status: GreenApiInstanceStatus.CONNECTED,
    pendingDisconnect: false,
  },
};

export const NotConnected: Story = {
  render(args) {
    const [pendingQrCode, setPendingQrCode] = useState<boolean>();
    const [qrCode, setQrCode] = useState<string>();
    const onGenerateQrCode = () => {
      setPendingQrCode(true);
      setTimeout(() => {
        setPendingQrCode(false);
        setQrCode(
          `iVBORw0KGgoAAAANSUhEUgAAARQAAAEUCAYAAADqcMl5AAAAAklEQVR4AewaftIAABJASURBVO3BQY7YypLAQFLo+1+Z42WuChBUbb8/yAj7g7XWuuBhrbUueVhrrUse1lrrkoe11rrkYa21LnlYa61LHtZa65KHtda65GGttS55WGutSx7WWuuSh7XWuuRhrbUueVhrrUse1lrrkh8+UvmbKiaVf6liUpkqJpWpYlJ5o+ILlaliUjmpeENlqphUpooTlZsq3lA5qZhUTiomlb+p4ouHtda65GGttS55WGutS364rOImlTcqvlA5qTipeENlqphUTlTeqDhROamYVE4q3qg4UZkqJpWTiknlROWkYlL5TRU3qdz0sNZalzystdYlD2utdckPv0zljYo3Kk5UpopJZaqYVCaVqWJSmSqmiknlpGJS+UJlqviiYlKZVKaKLyreqJhUpoqTihOVE5XfpPJGxW96WGutSx7WWuuSh7XWuuSH/3EqU8VUMalMFZPKVHGiMlVMKlPFFxUnKlPFicpJxRsVk8qk8kbFGxW/SeWLiknl/5OHtda65GGttS55WGutS374H1cxqZxUnFScqJyoTBWTyhcqU8VUMal8ofJGxVRxonKi8kbFScWkclIxVZyonKhMFf+fPKy11iUPa611ycNaa13ywy+r+Jcq/iWVqeJEZaqYKr6omFSmijdUJpWpYlKZKm5SmSomlZOKE5UvKm6q+C95WGutSx7WWuuSh7XWuuSHy1T+JpWpYlKZKiaVqWJSmSomlaliUjlRmSomlaliUpkqblKZKk4qJpWpYlKZKiaVqWJSmSomlaliUjlRmSomlaliUjlRmSpOVP7LHtZa65KHtda65GGttS6xP/gfpvJGxU0qJxWTyknFFypfVLyhMlWcqJxUTCpfVPyXqEwV/588rLXWJQ9rrXXJw1prXWJ/8IHKVDGpnFRMKm9UnKi8UfGGylQxqUwVX6hMFW+o/E0Vk8pUMalMFScqU8WkMlWcqEwVk8pU8YXKVDGpTBUnKlPFpHJS8cXDWmtd8rDWWpc8rLXWJT/8x1S8ofI3qUwVJxUnKicVU8Wk8kbFGypTxRcVX6icqJyonFS8oXJScVIxqbyhMlVMKicVNz2stdYlD2utdcnDWmtd8sNHFV+ofFExqZxUvKHyX6IyVUwqb6hMFVPFpHJSMamcVJyoTBWTyknFGyq/SeWNijdU/qWHtda65GGttS55WGutS+wPLlKZKt5QmSomlaniROWk4kTli4ovVE4qTlTeqHhDZao4UXmjYlL5ouINlZOKSeWk4kRlqjhRmSomlZOKmx7WWuuSh7XWuuRhrbUusT/4QOWLihOVqWJSOak4UZkqTlROKiaVqeJE5aRiUjmpmFROKk5UpopJ5aRiUjmp+ELlpOINlZOKSWWqmFSmikllqnhDZar4TQ9rrXXJw1prXfKw1lqX2B/8IpWTikllqphUTiq+UJkq3lA5qZhUpooTlaniRGWqOFF5o2JSmSomlaliUjmp+ELljYpJ5aaKSWWqOFE5qZhUTiq+eFhrrUse1lrrkoe11rrkh8tUpooTlROVqWJS+ULlRGWq+EJlqrhJZap4o+JE5Q2VqeKNihOVqWJSmSpOVN6omFTeUDlRmSqmiknljYqbHtZa65KHtda65GGttS754SOVqWJSmSpOKk5UpoovKk5UJpU3KiaVE5WpYqqYVG5SuanijYpJZaqYKiaVE5WpYqqYVKaKSWWqmFTeqDhROan4lx7WWuuSh7XWuuRhrbUu+eE/RuWkYlKZKt5Quanib6o4UZkq3qg4UZkqJpWp4guVqeILlS8q3qiYVE5UpopJ5UTlb3pYa61LHtZa65KHtda65IfLVE5UpopJZaqYVKaKLyomlaliUjlR+U0qU8UXKlPFpDJVnKicqJxUTBVfVEwqU8Wk8obKVDFVTConKlPFpHKTylTxxcNaa13ysNZalzystdYlP1xWMalMFW+ofKHyRsWkMlWcqEwV/1LFScWkcqIyVUwqX6hMFZPKVHGiMlWcVJyofFHxm1ROKiaVmx7WWuuSh7XWuuRhrbUu+eGjiknlRGWqOKmYVCaVqeKkYlKZVN5Q+ULlROUNlTcqTiomlUllqphUpopJ5W9SOak4qfiXKk5UpoqTipse1lrrkoe11rrkYa21LvnhI5WpYlKZKiaVqWJSeUPlX6qYVKaKqWJSmSq+qJhU3lCZKk5U3qg4UTlRmSomlaniRGWqmFSmijdUTiomlZOKqWJSeaPii4e11rrkYa21LnlYa61Lfvio4jdVTCpTxaQyVdyk8oXKFypfVEwqJxUnKlPFicobFZPKVDGpvKEyVZxUnKhMFVPFicr/soe11rrkYa21LnlYa61LfvhI5SaVk4qbKiaVv6liUvmi4kRlqphUJpU3VE4qJpWpYlI5UXlDZap4Q2WqmCq+qJhUbqr4TQ9rrXXJw1prXfKw1lqX2B98oDJVTCpTxd+kclJxk8pJxd+kMlVMKm9UnKhMFZPKFxUnKlPFicobFScqU8WkclJxonJTxU0Pa611ycNaa13ysNZal9gf/EUqJxWTylQxqUwVN6mcVEwqJxVvqHxR8YXKGxVvqEwVJypTxW9SeaNiUpkqJpUvKiaVk4pJZar44mGttS55WGutSx7WWuuSHz5SOan4ouKk4g2VqWJSmSreqJhU3lB5o+I3VZyovKEyVUwqJxU3qZxU3KQyVbyh8oXKVHHTw1prXfKw1lqXPKy11iU/fFRxovKGyhcVk8pUcVLxhspUMVWcqJxUTCpfqLxR8YXKVDGpnFR8ofJGxYnKVHGTyknFpPJf8rDWWpc8rLXWJQ9rrXWJ/cEHKicVb6hMFScqU8WJyknFpDJV/CaVk4pJ5aTiC5WpYlL5omJSmSomlZOKN1ROKiaVk4oTlZOKSWWqOFGZKiaVqeKmh7XWuuRhrbUueVhrrUvsDz5QmSomlaliUrmpYlKZKk5UTiomlTcqJpWp4kRlqphU/ksqblKZKr5QmSq+UJkqTlRuqphUTipuelhrrUse1lrrkoe11rrkh48qJpWpYlI5qXhD5QuVqeKLihOVqeK/pOINlROVk4pJZaqYKiaVk4ovVG5SOal4Q+WNit/0sNZalzystdYlD2utdckPH6lMFZPKFypTxYnKVHFS8ZtUpopJ5aRiqvibVKaKLyomlROVNypOVKaKNyomlROVL1SmihOVqWJSOan44mGttS55WGutSx7WWuuSHy5TmSomlTcq3qj4l1SmipOKE5Wp4m+qeKPii4oTlTdUflPFpDJVnKicVLxR8S89rLXWJQ9rrXXJw1prXWJ/8A+p/EsVv0nlpOINlTcqTlT+pYoTlaliUpkqvlB5o+JE5V+q+Jse1lrrkoe11rrkYa21LrE/+IdUTiomlZOKE5WTihOVmyomlaliUvmbKiaVk4oTlTcqJpUvKr5QmSomlaniDZU3KiaVNypuelhrrUse1lrrkoe11rrkh8tUTireUJkq/iaVqWJSmSq+qJhUpoo3VKaKSWWqmFROKk5U3qh4o2JSmSomlaliUnlDZap4Q2WqOFGZVN6o+E0Pa611ycNaa13ysNZal9gf/EUqU8WkMlVMKicVX6h8UXGi8kbFpHJSMalMFZPKGxUnKlPFpDJVTCpvVJyoTBWTylQxqbxR8YXKVPGGyhsVNz2stdYlD2utdcnDWmtdYn/wgcpUMalMFW+onFScqNxU8YXKVHGi8kXFpHJSMalMFZPKb6r4l1Smiknli4pJ5aTiRGWqmFSmipse1lrrkoe11rrkYa21LrE/+IdUpoo3VN6omFSmikllqphUTireUDmpOFE5qZhUflPFpDJVTConFZPKVHGi8kbFGypvVJyovFFxonJS8cXDWmtd8rDWWpc8rLXWJT/8MpWp4kTlpOKkYlKZVKaKk4qTihOVk4qpYlKZVKaKqWJSOak4UZkqJpWp4qaKN1ROKiaVqWJSeaNiUpkqTlSmii9U/qaHtda65GGttS55WGutS364TGWqmFSmijdUpopJ5aTiROU3VUwqU8VU8TepTBWTylQxqUwVU8WkMlVMKm9UfKHyRsWk8obKGyonFVPFicpND2utdcnDWmtd8rDWWpfYH/yHqXxRcaJyUjGp3FTxhspUMalMFTepnFR8ofJGxaQyVUwqX1S8oTJV3KTyRcVND2utdcnDWmtd8rDWWpfYH3ygclJxonJSMalMFScqU8WkMlVMKm9U3KTyRcVvUnmjYlKZKk5U3qg4Ubmp4iaVqeINlZOKmx7WWuuSh7XWuuRhrbUusT/4RSpTxYnKGxU3qUwVk8obFScqU8VNKicVk8pUMamcVHyhMlW8ofJGxaRyUjGpTBVvqHxRcaLyRsUXD2utdcnDWmtd8rDWWpfYH1ykMlVMKlPFGyq/qeJEZaq4SeWkYlKZKv4mlTcqTlROKt5QmSomlaniROWkYlKZKiaVqWJSmSpOVKaKSWWquOlhrbUueVhrrUse1lrrkh8+UjlROVF5o2JSmSp+U8WkMlW8ofI3qZxUfFFxojJVnFRMKicVb1R8UTGp3FQxqUwVJyonKlPFFw9rrXXJw1prXfKw1lqX/HBZxaQyVUwqU8WJylQxqZxUnKjcpPJFxaRyovKbVKaKE5UTlTcqJpVJ5URlqnij4o2Kk4qbKiaVk4qbHtZa65KHtda65GGttS6xP/hA5aRiUpkqJpWTikllqnhD5aTiDZWTihOVNyomlTcqJpWp4kRlqjhROak4UZkqJpWpYlI5qThReaNiUpkqJpWpYlI5qfiXHtZa65KHtda65GGttS754aOKSeWk4o2KSeULlaliUplUvqiYVKaKqWJSeaNiUvlNFTepTBUnKlPFpPKGyknFpHKiMlW8oTJVnKicVEwqU8UXD2utdcnDWmtd8rDWWpfYH/yHqJxUnKhMFScqU8UXKicVJyonFScqU8UXKlPFFyonFTepnFScqLxRcaIyVXyhclIxqZxUfPGw1lqXPKy11iUPa611yQ8fqUwVk8pJxUnFicpUMamcVHyh8psq3qg4UTmpmComlTcqTiomlZOKNypOVKaKqWJSOVF5Q+WNipOKf+lhrbUueVhrrUse1lrrEvuDX6RyU8VNKlPFpDJVTCpTxaRyUjGpnFS8oTJVTConFV+oTBWTyknFicpJxYnKScWkMlWcqEwVJypTxaTyRsWkMlXc9LDWWpc8rLXWJQ9rrXWJ/cEHKm9UTCpTxYnKFxUnKlPFGypvVEwqU8WkMlVMKlPFpPJFxW9SOak4UTmpOFGZKv4mlZOK/7KHtda65GGttS55WGutS+wPPlD5ouJEZaqYVKaKN1S+qPhCZaqYVE4qTlT+SypOVKaKSWWqmFSmiknlpOILlZOKSeWmiknlpOKmh7XWuuRhrbUueVhrrUt++KjiN1V8oXJSMan8TRUnFZPKicpJxaQyVbyhMlVMKicqb1T8JpWTipOKE5WTijdUJpWp4m96WGutSx7WWuuSh7XWuuSHj1T+poo3KiaVSeWk4iaVqWJSmSq+qJhU3lCZKm6qmFQmlanii4oTlTdUTiqmiknlRGWqeEPljYovHtZa65KHtda65GGttS754bKKm1TeUDmpmFSmihOVqWJSOamYVN6o+Jsq3lB5Q+Wk4kTlRGWqmFTeUDmpOFF5o+KLiknlNz2stdYlD2utdcnDWmtdYn/wgcpUMam8UTGpTBVfqEwVX6hMFX+TylTxhspvqphUpooTlS8q3lB5o2JSmSpOVH5TxYnKVPHFw1prXfKw1lqXPKy11iU//I9TeaNiUvmi4guVm1TeqJhU3qj4TRWTylQxqUwqJxVTxW9SmSreUPkve1hrrUse1lrrkoe11rrkh/9nKv4mlaliUjmp+E0qJypTxRsqU8VJxYnKVHGiMlWcqLyh8oXKGyonFZPKVDGpnFTc9LDWWpc8rLXWJQ9rrXXJD7+s4jdVvKEyVbyhMlVMKlPFb1KZKqaKSWWqOFE5qZhU3qiYKt6oOFGZKiaVqWKqmFSmihOVqWJSOamYVKaKSeWk4jc9rLXWJQ9rrXXJw1prXfLDZSp/k8pJxVQxqdxUMalMFZPKVHGi8kXFicpUMam8UTGpTConFW+ovFExqUwVJypTxVRxUnGiMlVMKm+onFR88bDWWpc8rLXWJQ9rrXWJ/cFaa13wsNZalzystdYlD2utdcnDWmtd8rDWWpc8rLXWJQ9rrXXJw1prXfKw1lqXPKy11iUPa611ycNaa13ysNZalzystdYlD2utdcn/ARucnGaOkcWVAAAAAElFTkSuQmCC`
        );
      }, 1_000);
    };
    return (
      <ConnectedGreenApiInstance
        {...args}
        pendingQr={pendingQrCode}
        qrCode={qrCode}
      />
    );
  },
  args: {
    status: GreenApiInstanceStatus.NOT_CONNECTED,
  },
};

export const InvalidGreenApiData: Story = {
  args: {
    status: GreenApiInstanceStatus.INVALID_GREEN_API_INSTANCE_INFO,
  },
};
